language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-25.0.1

    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

